/*==========================================================
 LATINADVISOR
 COUNTRIES MODULE
 VERSION 1.0
 ----------------------------------------------------------
 Listado estándar de países (nombre en español + indicativo
 telefónico internacional). Es la única fuente de verdad para:

   - El select "País" del estudiante (student.js), que alimenta
     directamente pricing.js#isCountryEligibleForMedicalExams.
   - El selector de indicativo telefónico (student.js), que es
     INDEPENDIENTE del país del estudiante (ver
     student.js#parsePhoneNumber / #findDialCodeByCountryName).

 Dato estático de referencia, no de negocio — igual filosofía
 que COURSE_TYPE_PRIORITY en database.js.
==========================================================*/

const WORLD_COUNTRIES = [

    { name: "Afganistán", iso2: "AF", dialCode: "+93" },
    { name: "Albania", iso2: "AL", dialCode: "+355" },
    { name: "Alemania", iso2: "DE", dialCode: "+49" },
    { name: "Andorra", iso2: "AD", dialCode: "+376" },
    { name: "Angola", iso2: "AO", dialCode: "+244" },
    { name: "Anguila", iso2: "AI", dialCode: "+1264" },
    { name: "Antigua y Barbuda", iso2: "AG", dialCode: "+1268" },
    { name: "Arabia Saudita", iso2: "SA", dialCode: "+966" },
    { name: "Argelia", iso2: "DZ", dialCode: "+213" },
    { name: "Argentina", iso2: "AR", dialCode: "+54" },
    { name: "Armenia", iso2: "AM", dialCode: "+374" },
    { name: "Aruba", iso2: "AW", dialCode: "+297" },
    { name: "Australia", iso2: "AU", dialCode: "+61" },
    { name: "Austria", iso2: "AT", dialCode: "+43" },
    { name: "Azerbaiyán", iso2: "AZ", dialCode: "+994" },
    { name: "Bahamas", iso2: "BS", dialCode: "+1242" },
    { name: "Bangladés", iso2: "BD", dialCode: "+880" },
    { name: "Barbados", iso2: "BB", dialCode: "+1246" },
    { name: "Baréin", iso2: "BH", dialCode: "+973" },
    { name: "Bélgica", iso2: "BE", dialCode: "+32" },
    { name: "Belice", iso2: "BZ", dialCode: "+501" },
    { name: "Benín", iso2: "BJ", dialCode: "+229" },
    { name: "Bermudas", iso2: "BM", dialCode: "+1441" },
    { name: "Bielorrusia", iso2: "BY", dialCode: "+375" },
    { name: "Bolivia", iso2: "BO", dialCode: "+591" },
    { name: "Bosnia y Herzegovina", iso2: "BA", dialCode: "+387" },
    { name: "Botsuana", iso2: "BW", dialCode: "+267" },
    { name: "Brasil", iso2: "BR", dialCode: "+55" },
    { name: "Brunéi", iso2: "BN", dialCode: "+673" },
    { name: "Bulgaria", iso2: "BG", dialCode: "+359" },
    { name: "Burkina Faso", iso2: "BF", dialCode: "+226" },
    { name: "Burundi", iso2: "BI", dialCode: "+257" },
    { name: "Bután", iso2: "BT", dialCode: "+975" },
    { name: "Cabo Verde", iso2: "CV", dialCode: "+238" },
    { name: "Camboya", iso2: "KH", dialCode: "+855" },
    { name: "Camerún", iso2: "CM", dialCode: "+237" },
    { name: "Canadá", iso2: "CA", dialCode: "+1" },
    { name: "Catar", iso2: "QA", dialCode: "+974" },
    { name: "Chad", iso2: "TD", dialCode: "+235" },
    { name: "Chile", iso2: "CL", dialCode: "+56" },
    { name: "China", iso2: "CN", dialCode: "+86" },
    { name: "Chipre", iso2: "CY", dialCode: "+357" },
    { name: "Ciudad del Vaticano", iso2: "VA", dialCode: "+379" },
    { name: "Colombia", iso2: "CO", dialCode: "+57" },
    { name: "Comoras", iso2: "KM", dialCode: "+269" },
    { name: "Corea del Norte", iso2: "KP", dialCode: "+850" },
    { name: "Corea del Sur", iso2: "KR", dialCode: "+82" },
    { name: "Costa de Marfil", iso2: "CI", dialCode: "+225" },
    { name: "Costa Rica", iso2: "CR", dialCode: "+506" },
    { name: "Croacia", iso2: "HR", dialCode: "+385" },
    { name: "Cuba", iso2: "CU", dialCode: "+53" },
    { name: "Curazao", iso2: "CW", dialCode: "+599" },
    { name: "Dinamarca", iso2: "DK", dialCode: "+45" },
    { name: "Dominica", iso2: "DM", dialCode: "+1767" },
    { name: "Ecuador", iso2: "EC", dialCode: "+593" },
    { name: "Egipto", iso2: "EG", dialCode: "+20" },
    { name: "El Salvador", iso2: "SV", dialCode: "+503" },
    { name: "Emiratos Árabes Unidos", iso2: "AE", dialCode: "+971" },
    { name: "Eritrea", iso2: "ER", dialCode: "+291" },
    { name: "Eslovaquia", iso2: "SK", dialCode: "+421" },
    { name: "Eslovenia", iso2: "SI", dialCode: "+386" },
    { name: "España", iso2: "ES", dialCode: "+34" },
    { name: "Estados Unidos", iso2: "US", dialCode: "+1" },
    { name: "Estonia", iso2: "EE", dialCode: "+372" },
    { name: "Etiopía", iso2: "ET", dialCode: "+251" },
    { name: "Filipinas", iso2: "PH", dialCode: "+63" },
    { name: "Finlandia", iso2: "FI", dialCode: "+358" },
    { name: "Fiyi", iso2: "FJ", dialCode: "+679" },
    { name: "Francia", iso2: "FR", dialCode: "+33" },
    { name: "Gabón", iso2: "GA", dialCode: "+241" },
    { name: "Gambia", iso2: "GM", dialCode: "+220" },
    { name: "Georgia", iso2: "GE", dialCode: "+995" },
    { name: "Ghana", iso2: "GH", dialCode: "+233" },
    { name: "Gibraltar", iso2: "GI", dialCode: "+350" },
    { name: "Granada", iso2: "GD", dialCode: "+1473" },
    { name: "Grecia", iso2: "GR", dialCode: "+30" },
    { name: "Groenlandia", iso2: "GL", dialCode: "+299" },
    { name: "Guadalupe", iso2: "GP", dialCode: "+590" },
    { name: "Guam", iso2: "GU", dialCode: "+1671" },
    { name: "Guatemala", iso2: "GT", dialCode: "+502" },
    { name: "Guayana Francesa", iso2: "GF", dialCode: "+594" },
    { name: "Guinea", iso2: "GN", dialCode: "+224" },
    { name: "Guinea-Bisáu", iso2: "GW", dialCode: "+245" },
    { name: "Guinea Ecuatorial", iso2: "GQ", dialCode: "+240" },
    { name: "Guyana", iso2: "GY", dialCode: "+592" },
    { name: "Haití", iso2: "HT", dialCode: "+509" },
    { name: "Honduras", iso2: "HN", dialCode: "+504" },
    { name: "Hong Kong", iso2: "HK", dialCode: "+852" },
    { name: "Hungría", iso2: "HU", dialCode: "+36" },
    { name: "India", iso2: "IN", dialCode: "+91" },
    { name: "Indonesia", iso2: "ID", dialCode: "+62" },
    { name: "Irak", iso2: "IQ", dialCode: "+964" },
    { name: "Irán", iso2: "IR", dialCode: "+98" },
    { name: "Irlanda", iso2: "IE", dialCode: "+353" },
    { name: "Islandia", iso2: "IS", dialCode: "+354" },
    { name: "Islas Caimán", iso2: "KY", dialCode: "+1345" },
    { name: "Islas Cook", iso2: "CK", dialCode: "+682" },
    { name: "Islas Feroe", iso2: "FO", dialCode: "+298" },
    { name: "Islas Marshall", iso2: "MH", dialCode: "+692" },
    { name: "Islas Salomón", iso2: "SB", dialCode: "+677" },
    { name: "Islas Turcas y Caicos", iso2: "TC", dialCode: "+1649" },
    { name: "Islas Vírgenes Británicas", iso2: "VG", dialCode: "+1284" },
    { name: "Islas Vírgenes de EE. UU.", iso2: "VI", dialCode: "+1340" },
    { name: "Israel", iso2: "IL", dialCode: "+972" },
    { name: "Italia", iso2: "IT", dialCode: "+39" },
    { name: "Jamaica", iso2: "JM", dialCode: "+1876" },
    { name: "Japón", iso2: "JP", dialCode: "+81" },
    { name: "Jordania", iso2: "JO", dialCode: "+962" },
    { name: "Kazajistán", iso2: "KZ", dialCode: "+7" },
    { name: "Kenia", iso2: "KE", dialCode: "+254" },
    { name: "Kirguistán", iso2: "KG", dialCode: "+996" },
    { name: "Kiribati", iso2: "KI", dialCode: "+686" },
    { name: "Kuwait", iso2: "KW", dialCode: "+965" },
    { name: "Laos", iso2: "LA", dialCode: "+856" },
    { name: "Lesoto", iso2: "LS", dialCode: "+266" },
    { name: "Letonia", iso2: "LV", dialCode: "+371" },
    { name: "Líbano", iso2: "LB", dialCode: "+961" },
    { name: "Liberia", iso2: "LR", dialCode: "+231" },
    { name: "Libia", iso2: "LY", dialCode: "+218" },
    { name: "Liechtenstein", iso2: "LI", dialCode: "+423" },
    { name: "Lituania", iso2: "LT", dialCode: "+370" },
    { name: "Luxemburgo", iso2: "LU", dialCode: "+352" },
    { name: "Macao", iso2: "MO", dialCode: "+853" },
    { name: "Macedonia del Norte", iso2: "MK", dialCode: "+389" },
    { name: "Madagascar", iso2: "MG", dialCode: "+261" },
    { name: "Malasia", iso2: "MY", dialCode: "+60" },
    { name: "Malaui", iso2: "MW", dialCode: "+265" },
    { name: "Maldivas", iso2: "MV", dialCode: "+960" },
    { name: "Malí", iso2: "ML", dialCode: "+223" },
    { name: "Malta", iso2: "MT", dialCode: "+356" },
    { name: "Marruecos", iso2: "MA", dialCode: "+212" },
    { name: "Martinica", iso2: "MQ", dialCode: "+596" },
    { name: "Mauricio", iso2: "MU", dialCode: "+230" },
    { name: "Mauritania", iso2: "MR", dialCode: "+222" },
    { name: "México", iso2: "MX", dialCode: "+52" },
    { name: "Micronesia", iso2: "FM", dialCode: "+691" },
    { name: "Moldavia", iso2: "MD", dialCode: "+373" },
    { name: "Mónaco", iso2: "MC", dialCode: "+377" },
    { name: "Mongolia", iso2: "MN", dialCode: "+976" },
    { name: "Montenegro", iso2: "ME", dialCode: "+382" },
    { name: "Mozambique", iso2: "MZ", dialCode: "+258" },
    { name: "Myanmar", iso2: "MM", dialCode: "+95" },
    { name: "Namibia", iso2: "NA", dialCode: "+264" },
    { name: "Nauru", iso2: "NR", dialCode: "+674" },
    { name: "Nepal", iso2: "NP", dialCode: "+977" },
    { name: "Nicaragua", iso2: "NI", dialCode: "+505" },
    { name: "Níger", iso2: "NE", dialCode: "+227" },
    { name: "Nigeria", iso2: "NG", dialCode: "+234" },
    { name: "Noruega", iso2: "NO", dialCode: "+47" },
    { name: "Nueva Caledonia", iso2: "NC", dialCode: "+687" },
    { name: "Nueva Zelanda", iso2: "NZ", dialCode: "+64" },
    { name: "Omán", iso2: "OM", dialCode: "+968" },
    { name: "Países Bajos", iso2: "NL", dialCode: "+31" },
    { name: "Pakistán", iso2: "PK", dialCode: "+92" },
    { name: "Palaos", iso2: "PW", dialCode: "+680" },
    { name: "Palestina", iso2: "PS", dialCode: "+970" },
    { name: "Panamá", iso2: "PA", dialCode: "+507" },
    { name: "Papúa Nueva Guinea", iso2: "PG", dialCode: "+675" },
    { name: "Paraguay", iso2: "PY", dialCode: "+595" },
    { name: "Perú", iso2: "PE", dialCode: "+51" },
    { name: "Polinesia Francesa", iso2: "PF", dialCode: "+689" },
    { name: "Polonia", iso2: "PL", dialCode: "+48" },
    { name: "Portugal", iso2: "PT", dialCode: "+351" },
    { name: "Puerto Rico", iso2: "PR", dialCode: "+1787" },
    { name: "Reino Unido", iso2: "GB", dialCode: "+44" },
    { name: "República Centroafricana", iso2: "CF", dialCode: "+236" },
    { name: "República Checa", iso2: "CZ", dialCode: "+420" },
    { name: "República del Congo", iso2: "CG", dialCode: "+242" },
    { name: "República Democrática del Congo", iso2: "CD", dialCode: "+243" },
    { name: "República Dominicana", iso2: "DO", dialCode: "+1849" },
    { name: "Ruanda", iso2: "RW", dialCode: "+250" },
    { name: "Rumanía", iso2: "RO", dialCode: "+40" },
    { name: "Rusia", iso2: "RU", dialCode: "+7" },
    { name: "Samoa", iso2: "WS", dialCode: "+685" },
    { name: "San Cristóbal y Nieves", iso2: "KN", dialCode: "+1869" },
    { name: "San Marino", iso2: "SM", dialCode: "+378" },
    { name: "San Vicente y las Granadinas", iso2: "VC", dialCode: "+1784" },
    { name: "Santa Lucía", iso2: "LC", dialCode: "+1758" },
    { name: "Santo Tomé y Príncipe", iso2: "ST", dialCode: "+239" },
    { name: "Senegal", iso2: "SN", dialCode: "+221" },
    { name: "Serbia", iso2: "RS", dialCode: "+381" },
    { name: "Seychelles", iso2: "SC", dialCode: "+248" },
    { name: "Sierra Leona", iso2: "SL", dialCode: "+232" },
    { name: "Singapur", iso2: "SG", dialCode: "+65" },
    { name: "Siria", iso2: "SY", dialCode: "+963" },
    { name: "Somalia", iso2: "SO", dialCode: "+252" },
    { name: "Sri Lanka", iso2: "LK", dialCode: "+94" },
    { name: "Suazilandia", iso2: "SZ", dialCode: "+268" },
    { name: "Sudáfrica", iso2: "ZA", dialCode: "+27" },
    { name: "Sudán", iso2: "SD", dialCode: "+249" },
    { name: "Sudán del Sur", iso2: "SS", dialCode: "+211" },
    { name: "Suecia", iso2: "SE", dialCode: "+46" },
    { name: "Suiza", iso2: "CH", dialCode: "+41" },
    { name: "Surinam", iso2: "SR", dialCode: "+597" },
    { name: "Tailandia", iso2: "TH", dialCode: "+66" },
    { name: "Taiwán", iso2: "TW", dialCode: "+886" },
    { name: "Tanzania", iso2: "TZ", dialCode: "+255" },
    { name: "Tayikistán", iso2: "TJ", dialCode: "+992" },
    { name: "Timor Oriental", iso2: "TL", dialCode: "+670" },
    { name: "Togo", iso2: "TG", dialCode: "+228" },
    { name: "Tonga", iso2: "TO", dialCode: "+676" },
    { name: "Trinidad y Tobago", iso2: "TT", dialCode: "+1868" },
    { name: "Túnez", iso2: "TN", dialCode: "+216" },
    { name: "Turkmenistán", iso2: "TM", dialCode: "+993" },
    { name: "Turquía", iso2: "TR", dialCode: "+90" },
    { name: "Tuvalu", iso2: "TV", dialCode: "+688" },
    { name: "Ucrania", iso2: "UA", dialCode: "+380" },
    { name: "Uganda", iso2: "UG", dialCode: "+256" },
    { name: "Uruguay", iso2: "UY", dialCode: "+598" },
    { name: "Uzbekistán", iso2: "UZ", dialCode: "+998" },
    { name: "Vanuatu", iso2: "VU", dialCode: "+678" },
    { name: "Venezuela", iso2: "VE", dialCode: "+58" },
    { name: "Vietnam", iso2: "VN", dialCode: "+84" },
    { name: "Yemen", iso2: "YE", dialCode: "+967" },
    { name: "Yibuti", iso2: "DJ", dialCode: "+253" },
    { name: "Zambia", iso2: "ZM", dialCode: "+260" },
    { name: "Zimbabue", iso2: "ZW", dialCode: "+263" }

];

/*
    Países con los que trabaja habitualmente LatinAdvisor — se
    muestran primero en el selector de indicativo telefónico
    (ver student.js#createPhoneCodeOptions), antes del resto del
    listado internacional completo, en este orden.
*/
const PRIORITY_COUNTRY_CODES = ["CO", "MX", "CL", "AR", "PE", "US", "AU", "ES"];

/*
    El campo "Country" de GHL es un campo estándar del sistema que
    guarda el nombre del país en INGLÉS (ej. "Colombia", "Spain",
    "Germany"), mientras que WORLD_COUNTRIES está en español — por
    eso "Colombia"/"Chile"/etc. calzan por coincidencia (se escriben
    igual en ambos idiomas), pero la mayoría no. Se usa como
    respaldo en student.js#findCountryByName cuando el nombre no
    calza directo contra el español. Algunas entradas traen más de
    un alias porque ciertos datasets de países usan el nombre formal
    largo (ej. "Bolivia, Plurinational State of") en vez del nombre
    común — no se pudo confirmar cuál usa GHL exactamente sin una
    prueba en vivo, así que se aceptan ambas variantes.
*/
const ENGLISH_COUNTRY_ALIASES = {
    AF: ["afghanistan"], AL: ["albania"], DE: ["germany"], AD: ["andorra"],
    AO: ["angola"], AI: ["anguilla"], AG: ["antigua and barbuda"],
    SA: ["saudi arabia"], DZ: ["algeria"], AR: ["argentina"], AM: ["armenia"],
    AW: ["aruba"], AU: ["australia"], AT: ["austria"], AZ: ["azerbaijan"],
    BS: ["bahamas"], BD: ["bangladesh"], BB: ["barbados"], BH: ["bahrain"],
    BE: ["belgium"], BZ: ["belize"], BJ: ["benin"], BM: ["bermuda"],
    BY: ["belarus"], BO: ["bolivia", "bolivia, plurinational state of"],
    BA: ["bosnia and herzegovina"], BW: ["botswana"], BR: ["brazil"],
    BN: ["brunei", "brunei darussalam"], BG: ["bulgaria"],
    BF: ["burkina faso"], BI: ["burundi"], BT: ["bhutan"],
    CV: ["cape verde"], KH: ["cambodia"], CM: ["cameroon"], CA: ["canada"],
    QA: ["qatar"], TD: ["chad"], CL: ["chile"], CN: ["china"], CY: ["cyprus"],
    VA: ["vatican", "vatican city", "holy see"], CO: ["colombia"],
    KM: ["comoros"],
    KP: ["north korea", "korea, democratic people's republic of"],
    KR: ["south korea", "korea, republic of"],
    CI: ["ivory coast", "cote d'ivoire", "côte d'ivoire"],
    CR: ["costa rica"], HR: ["croatia"], CU: ["cuba"],
    CW: ["curacao", "curaçao"], DK: ["denmark"], DM: ["dominica"],
    EC: ["ecuador"], EG: ["egypt"], SV: ["el salvador"],
    AE: ["united arab emirates"], ER: ["eritrea"], SK: ["slovakia"],
    SI: ["slovenia"], ES: ["spain"], US: ["united states"], EE: ["estonia"],
    ET: ["ethiopia"], PH: ["philippines"], FI: ["finland"], FJ: ["fiji"],
    FR: ["france"], GA: ["gabon"], GM: ["gambia"], GE: ["georgia"],
    GH: ["ghana"], GI: ["gibraltar"], GD: ["grenada"], GR: ["greece"],
    GL: ["greenland"], GP: ["guadeloupe"], GU: ["guam"], GT: ["guatemala"],
    GF: ["french guiana"], GN: ["guinea"], GW: ["guinea-bissau"],
    GQ: ["equatorial guinea"], GY: ["guyana"], HT: ["haiti"],
    HN: ["honduras"], HK: ["hong kong"], HU: ["hungary"], IN: ["india"],
    ID: ["indonesia"], IQ: ["iraq"], IR: ["iran", "iran, islamic republic of"],
    IE: ["ireland"], IS: ["iceland"], KY: ["cayman islands"],
    CK: ["cook islands"], FO: ["faroe islands"], MH: ["marshall islands"],
    SB: ["solomon islands"], TC: ["turks and caicos islands"],
    VG: ["virgin islands, british"], VI: ["virgin islands, u.s", "virgin islands, us"],
    IL: ["israel"], IT: ["italy"], JM: ["jamaica"], JP: ["japan"],
    JO: ["jordan"], KZ: ["kazakhstan"], KE: ["kenya"], KG: ["kyrgyzstan"],
    KI: ["kiribati"], KW: ["kuwait"], LA: ["laos", "lao people's democratic republic"],
    LS: ["lesotho"], LV: ["latvia"], LB: ["lebanon"], LR: ["liberia"],
    LY: ["libya"], LI: ["liechtenstein"], LT: ["lithuania"],
    LU: ["luxembourg"], MO: ["macao", "macau"],
    MK: ["macedonia", "north macedonia", "macedonia, the former yugoslav republic of"],
    MG: ["madagascar"], MY: ["malaysia"], MW: ["malawi"], MV: ["maldives"],
    ML: ["mali"], MT: ["malta"], MA: ["morocco"], MQ: ["martinique"],
    MU: ["mauritius"], MR: ["mauritania"], MX: ["mexico"],
    FM: ["micronesia", "micronesia, federated states of"],
    MD: ["moldova", "moldova, republic of"], MC: ["monaco"],
    MN: ["mongolia"], ME: ["montenegro"], MZ: ["mozambique"],
    MM: ["myanmar", "burma"], NA: ["namibia"], NR: ["nauru"], NP: ["nepal"],
    NI: ["nicaragua"], NE: ["niger"], NG: ["nigeria"], NO: ["norway"],
    NC: ["new caledonia"], NZ: ["new zealand"], OM: ["oman"],
    NL: ["netherlands"], PK: ["pakistan"], PW: ["palau"],
    PS: ["palestine", "palestinian territory, occupied"], PA: ["panama"],
    PG: ["papua new guinea"], PY: ["paraguay"], PE: ["peru"],
    PF: ["french polynesia"], PL: ["poland"], PT: ["portugal"],
    PR: ["puerto rico"], GB: ["united kingdom"],
    CF: ["central african republic"], CZ: ["czech republic", "czechia"],
    CG: ["congo", "republic of the congo", "congo-brazzaville"],
    CD: ["democratic republic of the congo", "congo, the democratic republic of the", "congo-kinshasa"],
    DO: ["dominican republic"], RW: ["rwanda"], RO: ["romania"],
    RU: ["russia", "russian federation"], WS: ["samoa"],
    KN: ["saint kitts and nevis"], SM: ["san marino"],
    VC: ["saint vincent and the grenadines"], LC: ["saint lucia"],
    ST: ["sao tome and principe"], SN: ["senegal"], RS: ["serbia"],
    SC: ["seychelles"], SL: ["sierra leone"], SG: ["singapore"],
    SY: ["syria", "syrian arab republic"], SO: ["somalia"], LK: ["sri lanka"],
    SZ: ["swaziland", "eswatini"], ZA: ["south africa"], SD: ["sudan"],
    SS: ["south sudan"], SE: ["sweden"], CH: ["switzerland"],
    SR: ["suriname"], TH: ["thailand"], TW: ["taiwan", "taiwan, province of china"],
    TZ: ["tanzania", "tanzania, united republic of"], TJ: ["tajikistan"],
    TL: ["timor-leste", "east timor"], TG: ["togo"], TO: ["tonga"],
    TT: ["trinidad and tobago"], TN: ["tunisia"], TM: ["turkmenistan"],
    TR: ["turkey"], TV: ["tuvalu"], UA: ["ukraine"], UG: ["uganda"],
    UY: ["uruguay"], UZ: ["uzbekistan"], VU: ["vanuatu"],
    VE: ["venezuela", "venezuela, bolivarian republic of"], VN: ["vietnam"],
    YE: ["yemen"], DJ: ["djibouti"], ZM: ["zambia"], ZW: ["zimbabwe"]
};
